FROM nginx AS base
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY GoFood.Application/ ./GoFood.Application/
COPY GoFood/ ./GoFood/
RUN dotnet restore ./GoFood/ 
COPY . ./
RUN dotnet publish ./GoFood/GoFood.App.csproj -c Release -o out 
# RUN apt-get update && install iputils-ping


FROM base as final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/out/wwwroot .
COPY  nginx.conf /etc/nginx/nginx.conf

